// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunBackend(arg1) {
  return window['go']['main']['App']['RunBackend'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
